### ISSUE TITLE
Mention that go is a dependency

### ISSUE THREAD

**Issue by jessieay** [contraband/autopilot#18]
It might be nice to mention that go is a dependency of this lib. It took me a few minutes to realize that. :)

**Comment by afeld** [comment]
Alternative instructions could say "download the latest [release](https://github.com/concourse/autopilot/releases) and put it in your PATH", yeah? That wouldn't require Go.

**Comment by xoebus** [comment]
Thanks for the issue!

I've updated the instructions to suggest downloading the precompiled binaries rather than compiling them yourself.

P.S. GitHub has a handy listing of the type of source code in a project if you click the colored bar at the top of the file listing.

![screen shot 2016-08-31 at 17 48 22](https://cloud.githubusercontent.com/assets/38814/18151335/630f845e-6fa3-11e6-9e5f-edba5c7959ec.png)
